### Site Settings ###
title               : Sonish Sivarajkumar
description         : >-

                      <style>
                      .button {
                        display: block;
                        width: 115px;
                        height: 45px;
                        background: #007BFF;
                        padding: 10px;
                        text-align: center;
                        border-radius: 5px;
                        color: white;
                        font-weight: bold;
                        line-height: 25px;
                        margin-top: 10%;
                        margin-left: auto;
                        margin-right: auto;
                        text-decoration: none;
                        color: white;
                      }
                      </style>

                      Ph.D. Student in Machine Learning & Biomedical Informatics <a target='_blank' rel='noopener noreferrer' href='https://pitt.edu/'>@Pitt</a>.
                      This website is still under development. Please visit <a target='_blank' rel='noopener noreferrer' href='https://sonishsivarajkumar.github.io/homepage/'>@my older website</a>.
                      <a class='button' target='_blank' rel='noopener noreferrer' href='https://sonishsivarajkumar.github.io/assets/pdf/Sonish_Sivarajkumar_CV.pdf'>
                        CV/Resume
                      </a>
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : sonishsivarajkumar/sonishsivarajkumar.github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU@v2.2.2


### Plugins ###
plugins:
  - jemoji


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Sonish Sivarajkumar
  image             : https://sonishsivarajkumar.github.io/assets/img/portfolio_picture.jpg
# behance           : your_username
# dribbble          : your_username
  email             : sonish.sivarajkumar@gmail.com
# facebook          : your_username
  github            : sonishsivarajkumar
# gitlab            : your_username
# instagram         : your_username
  kaggle            : sonish2383
  linkedin          : sonish-sivarajkumar-7b2b19163
  medium            : sonish.sivarajkumar
# soundcloud        : lexorehead
# spotify           : your_username
# stackoverflow     : 7614810
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : sonish_sivaraj
# vimeo             : your_username
# youtube           : your_channel_name


### Posts ###
permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus: your-short-name-disqus                          # Your website Shortname on disqus


### Built-In Google Analytics ###
analytics:
  enabled: true                                        # Set true to enable analytics
  google:
    tracking_id: UA-172070520-1

# Custom Google Analytics (Enabled)
google_analytics: UA-172070520-1

### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments

### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
